### ISSUE TITLE
Rename some filenames.

### ISSUE THREAD

**Issue by CBenoit** [Lomadriel/WaitFreeHashMap#18]
There is currently only one example in the example folder, and it is in the `main.cpp` file.
We should rename it to `unordered_map_example.cpp` as it's easier to understand what is it.
Furthermore, we'll add more examples later.

**Comment by Lomadriel** [comment]
TODO:
- [ ] Move example/main.cpp to examples/unordered_map_example.cpp
- [ ] Move test/single_thread_test.cpp to tests/unordered_map_single_thread_test.cpp
