### ISSUE TITLE
Default hash function is not always perfect.

### ISSUE THREAD

**Issue by Lomadriel** [Lomadriel/WaitFreeHashMap#24]
https://github.com/Exerg/WaitFreeCollections/blob/93ecb9b008c92c9681b5e9fa99e68000647a97f8/include/wfc/unordered_map.hpp#L39-L46

This "hash function" is correct for the unordered_map but the return size doesn't match the key size. If sizeof(Key) <= sizeof(std::size_t) no problem. But in the other case, the hash function isn't "perfect" and as stated in the article this is a requirement for the hash function.

**Comment by CBenoit** [comment]
Fixed by https://github.com/Exerg/WaitFreeCollections/pull/26
