### ISSUE TITLE
Wrong error message in unordered_map constructor.

### ISSUE THREAD

**Issue by Lomadriel** [Lomadriel/WaitFreeHashMap#29]
https://github.com/Exerg/WaitFreeCollections/blob/5ccd6abe497de8472605cad5834e187813d3a8e9/include/wfc/unordered_map.hpp#L168-L171

Error message should be "Array length should be a power of four".
Moreover constructor parameter should be named "array_length" rather than "log_bucker_count".

**Comment by CBenoit** [comment]
Fixed by https://github.com/Exerg/WaitFreeCollections/pull/30.
