### ISSUE TITLE
maxFailCount

### ISSUE THREAD

**Issue by Lomadriel** [Lomadriel/WaitFreeHashMap#6]
As defined in the article:

> maxFailCount [...] is a user-defined constant used to bound the maximum number of times that a thread retries an operation after a CAS operation fails. If this bound is reached, then an expansion is forced at the position that the failing operation is attempting to modify.

Moreover the authors recommend to set this variable according to the expected number of threads that will compete for a single datanode in the hash map.

> The maxFailCount should be set to the expected number of threads that will compete for a single location in the hash map; in practice, the failCount never surpassed 3, but a value of 10 was used for testing. If maxFailCount is set too low, then the hash map may be unnecessarily expanded.

**Comment by Lomadriel** [comment]
I think it's a good idea to add this as a constructor argument.

**Comment by CBenoit** [comment]
Fixed by #31.
